"""
Telegram Bot for Owner Notifications

Sends alerts and daily reports to the platform owner.
"""
import asyncio
import aiohttp
from typing import Optional, Dict, Any
from datetime import datetime
import json

from .config import ai_settings


class TelegramNotifier:
    """Send notifications to owner via Telegram"""

    def __init__(self):
        self.token = ai_settings.TELEGRAM_BOT_TOKEN
        self.chat_id = ai_settings.TELEGRAM_OWNER_CHAT_ID
        self.base_url = f"https://api.telegram.org/bot{self.token}"

    @property
    def is_configured(self) -> bool:
        return bool(self.token and self.chat_id)

    async def send_message(
        self,
        text: str,
        parse_mode: str = "HTML",
        disable_notification: bool = False
    ) -> Dict[str, Any]:
        """Send a message to the owner"""
        if not self.is_configured:
            return {"error": "Telegram not configured"}

        url = f"{self.base_url}/sendMessage"
        payload = {
            "chat_id": self.chat_id,
            "text": text,
            "parse_mode": parse_mode,
            "disable_notification": disable_notification
        }

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(url, json=payload) as response:
                    return await response.json()
        except Exception as e:
            return {"error": str(e)}

    async def send_alert(
        self,
        title: str,
        message: str,
        level: str = "INFO",
        data: Optional[Dict] = None
    ):
        """Send an alert notification"""
        emoji_map = {
            "INFO": "ℹ️",
            "WARNING": "⚠️",
            "ERROR": "❌",
            "CRITICAL": "🚨",
            "SUCCESS": "✅",
            "MONEY": "💰"
        }
        emoji = emoji_map.get(level, "📢")

        text = f"{emoji} <b>{title}</b>\n\n{message}"

        if data:
            text += "\n\n<pre>" + json.dumps(data, ensure_ascii=False, indent=2)[:500] + "</pre>"

        text += f"\n\n🕐 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"

        return await self.send_message(text)

    async def send_new_signup_alert(
        self,
        tenant_name: str,
        tenant_email: str,
        plan: str = "FREE"
    ):
        """Alert when new tenant signs up"""
        await self.send_alert(
            title="Khách hàng mới đăng ký!",
            message=f"<b>{tenant_name}</b>\n📧 {tenant_email}\n📦 Gói: {plan}",
            level="SUCCESS"
        )

    async def send_payment_alert(
        self,
        tenant_name: str,
        amount: float,
        invoice_id: str
    ):
        """Alert when payment received"""
        await self.send_alert(
            title="Thanh toán mới!",
            message=f"<b>{tenant_name}</b>\n💵 {amount:,.0f} VND\n📄 Invoice: {invoice_id}",
            level="MONEY"
        )

    async def send_support_escalation(
        self,
        ticket_id: str,
        subject: str,
        user_email: str,
        conversation_summary: str
    ):
        """Alert when support escalated to human"""
        await self.send_alert(
            title="Yêu cầu hỗ trợ cần xử lý",
            message=f"🎫 Ticket: {ticket_id}\n📧 User: {user_email}\n\n<b>Vấn đề:</b> {subject}\n\n<b>Tóm tắt:</b>\n{conversation_summary[:500]}",
            level="WARNING"
        )

    async def send_error_alert(
        self,
        error_type: str,
        error_message: str,
        context: Optional[Dict] = None
    ):
        """Alert on system errors"""
        await self.send_alert(
            title=f"Lỗi hệ thống: {error_type}",
            message=error_message[:500],
            level="ERROR",
            data=context
        )

    async def send_daily_report(
        self,
        mrr: float,
        active_tenants: int,
        new_signups: int,
        churned: int,
        support_tickets: int,
        auto_resolved: int,
        uptime: float
    ):
        """Send daily business report"""
        report = f"""📊 <b>BÁO CÁO NGÀY {datetime.now().strftime('%d/%m/%Y')}</b>

💰 <b>Doanh thu</b>
• MRR: {mrr:,.0f} VND

👥 <b>Khách hàng</b>
• Active: {active_tenants}
• Mới: +{new_signups}
• Churn: -{churned}

🎫 <b>Support</b>
• Tickets: {support_tickets}
• AI resolved: {auto_resolved} ({auto_resolved/max(support_tickets,1)*100:.0f}%)

⚡ <b>System</b>
• Uptime: {uptime:.2f}%

---
🤖 Auto-generated by 9log AI
"""
        await self.send_message(report)

    async def send_usage_alert(
        self,
        tenant_name: str,
        usage_percent: int,
        credits_used: int,
        credits_limit: int
    ):
        """Alert when tenant reaches usage threshold"""
        if usage_percent >= 100:
            level = "ERROR"
            title = "Tenant đã hết quota!"
        elif usage_percent >= 80:
            level = "WARNING"
            title = "Tenant sắp hết quota"
        else:
            return  # Don't alert for low usage

        await self.send_alert(
            title=title,
            message=f"<b>{tenant_name}</b>\n📊 Sử dụng: {usage_percent}%\n💳 {credits_used:,}/{credits_limit:,} credits",
            level=level
        )


# Singleton instance
_notifier: Optional[TelegramNotifier] = None


def get_telegram_notifier() -> TelegramNotifier:
    """Get Telegram notifier instance"""
    global _notifier
    if _notifier is None:
        _notifier = TelegramNotifier()
    return _notifier


# Convenience functions
async def notify_owner(title: str, message: str, level: str = "INFO"):
    """Quick function to notify owner"""
    notifier = get_telegram_notifier()
    await notifier.send_alert(title, message, level)


async def notify_error(error_type: str, error_message: str):
    """Quick function to notify error"""
    notifier = get_telegram_notifier()
    await notifier.send_error_alert(error_type, error_message)
